

service: my-service
frameworkVersion: '3'
plugins:

  - serverless-offline
custom:
  dotenv:
    path: .env
 
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  
 
functions:
  app:
    handler: handler.handler
    events:
      - httpApi:
          path: /webhooks
          method: get
          request:
            parameters:
              querystrings:
                hub.mode: true
                hub.verify_token: true
                hub.challenge: true
 
 
 