service: catalogue1
 
frameworkVersion: "3"
 
provider:
  name: aws
  runtime: nodejs14.x
 
plugins:
  - serverless-offline
 
 
functions:
  hello:
    handler: product/catalogue/toInsert.createProduct
    timeout: 300
    events:
      - httpApi:
          path: /create
          method: post
  update:
    handler: product/catalogue/update.updateProduct
    timeout: 300
    events:
      - httpApi:
          path: /create
          method: put