service: catalogue1
 
frameworkVersion: "3"
 
provider:
  name: aws
  runtime: nodejs14.x
 
plugins:
  - serverless-offline
 
 
functions:
  hello:
    handler: toInsert.createProduct
    timeout: 300
    events:
      - httpApi:
          path: /create
          method: post
  update:
    handler: update.updateProduct
    timeout: 300
    events:
      - httpApi:
          path: /update
          method: put
  delete:
    handler: update.updateProduct
    timeout: 300
    events:
      - httpApi:
          path: /delete
          method: delete