service: cognito-registration

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1 
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminAddUserToGroup
      Resource: "*"

functions:
  registerUser:
    handler: userRegistration.handler
    timeout: 600
    events:
      - http:
          path: registerUser
          method: post
          cors: true # Enable CORS for API Gateway

  signin:
    handler: signin.handler
    events:
      - http:
          path: signin
          method: post
          cors: true

  authorizer:
    handler: authorizer.dynamicAuthorizer


  insertData:
    handler: insertintodynamodb.insertData
    events:
      - http:
          path: inventory
          method: post
          cors: true
          authorizer: authorizer
  getData:
    handler: getallInventory.getAllData
    events:
      - http:
          path: inventory
          method: get
          cors: true
          authorizer: authorizer
  updatedy:
    handler: updateInventory.updateQuantity
    events:
      - http:
          path: inventory/{inventory_id}
          method: put
          cors: true
          authorizer: authorizer
  deletedy:
    handler: deleteInventory.deleteProduct
    events:
      - http:
          path: inventory/{inventory_id}
          method: delete
          cors: true
          authorizer: authorizer
  getby:
    handler: getbyidInventory.getItemById
    events:
      - http:
          path: inventory/{inventory_id}
          method: get
          cors: true
          authorizer: authorizer
plugins:
  - serverless-offline
