  createtable:
    handler: rest_apis/inventory/createTable.createTable
    events:
      - http:
          path: create 
          method: post
          cors: true
  insertData:
    handler: rest_apis/inventory/insertintoInventory.insertData
    events:
      - http:
          path: inventory
          method: post
          cors: true
  getData:
    handler: rest_apis/inventory/getallInventory.getAllData
    events:
      - http:
          path: inventory
          method: get
          cors: true
  updatedy:
    handler: rest_apis/inventory/updateInventory.updateQuantity
    events:
      - http:
          path: inventory/{inventory_id}
          method: put
          cors: true
  deletedy:
    handler: rest_apis/inventory/deleteInventory.deleteProduct
    events:
      - http:
          path: inventory/{inventory_id}
          method: delete
          cors: true
  getby:
    handler: rest_apis/inventory/getbyidInventory.getItemById
    events:
      - http:
          path: inventory/{inventory_id}
          method: get
          cors: true